/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Color;
import javax.swing.JFrame;
import ProductManagement.*;
import bc_stationary_bll.*;
import java.sql.Date;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author Eldane
 */
public class frmAddProduct extends javax.swing.JFrame {

    /**
     * Creates new form frmAddProduct
     */
    
    public frmAddProduct() {
        initComponents();
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        this.getContentPane().setBackground(new Color(45,45,45));
        txtStatus.setEditable(false);
        
        Category category = new Category();
        ArrayList<Category> categories = category.select();
        
        for(Category c:categories){
            cmbCategory.addItem(c.getDescription());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegisterHeader = new javax.swing.JPanel();
        pnlRegisterHeader1 = new javax.swing.JPanel();
        lblAddProduct = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        btnAddProduct = new javax.swing.JButton();
        btnUpdateStock = new javax.swing.JButton();
        btnViewStock = new javax.swing.JButton();
        btnAddStock = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        pnlProjectInfo = new javax.swing.JPanel();
        lblProductInfo = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblProductModel = new javax.swing.JLabel();
        txtProductModel = new javax.swing.JTextField();
        lblProductCost = new javax.swing.JLabel();
        txtProductCost = new javax.swing.JTextField();
        lblProductSale = new javax.swing.JLabel();
        txtProductSale = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        pnlExistingCategory = new javax.swing.JPanel();
        cmbCategory = new javax.swing.JComboBox<>();
        pnlNewCategory = new javax.swing.JPanel();
        txtCategory = new javax.swing.JTextField();
        pnlInStock = new javax.swing.JPanel();
        lblInStock = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        numQuantity = new javax.swing.JSpinner();
        btnInsertProduct = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlRegisterHeader.setBackground(new java.awt.Color(255, 255, 0));
        pnlRegisterHeader.setPreferredSize(new java.awt.Dimension(1071, 530));

        pnlRegisterHeader1.setBackground(new java.awt.Color(204, 0, 0));
        pnlRegisterHeader1.setPreferredSize(new java.awt.Dimension(1307, 65));

        lblAddProduct.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblAddProduct.setForeground(new java.awt.Color(255, 255, 255));
        lblAddProduct.setText("Add Product");
        lblAddProduct.setAlignmentY(0.0F);

        javax.swing.GroupLayout pnlRegisterHeader1Layout = new javax.swing.GroupLayout(pnlRegisterHeader1);
        pnlRegisterHeader1.setLayout(pnlRegisterHeader1Layout);
        pnlRegisterHeader1Layout.setHorizontalGroup(
            pnlRegisterHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterHeader1Layout.createSequentialGroup()
                .addGap(607, 607, 607)
                .addComponent(lblAddProduct)
                .addContainerGap(738, Short.MAX_VALUE))
        );
        pnlRegisterHeader1Layout.setVerticalGroup(
            pnlRegisterHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterHeader1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lblAddProduct)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlRegisterHeaderLayout = new javax.swing.GroupLayout(pnlRegisterHeader);
        pnlRegisterHeader.setLayout(pnlRegisterHeaderLayout);
        pnlRegisterHeaderLayout.setHorizontalGroup(
            pnlRegisterHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
            .addGroup(pnlRegisterHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlRegisterHeaderLayout.createSequentialGroup()
                    .addComponent(pnlRegisterHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, 1490, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlRegisterHeaderLayout.setVerticalGroup(
            pnlRegisterHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
            .addGroup(pnlRegisterHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlRegisterHeaderLayout.createSequentialGroup()
                    .addComponent(pnlRegisterHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pnlMenu.setBackground(new java.awt.Color(40, 40, 40));

        btnAddProduct.setBackground(new java.awt.Color(204, 0, 0));
        btnAddProduct.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnAddProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnAddProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Images/Add1_Red.png"))); // NOI18N
        btnAddProduct.setText("Add Product");
        btnAddProduct.setBorder(null);
        btnAddProduct.setBorderPainted(false);
        btnAddProduct.setContentAreaFilled(false);
        btnAddProduct.setFocusPainted(false);
        btnAddProduct.setIconTextGap(30);
        btnAddProduct.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Images/Add1_Red.png"))); // NOI18N

        btnUpdateStock.setBackground(new java.awt.Color(40, 40, 40));
        btnUpdateStock.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnUpdateStock.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Images/Edit1.png"))); // NOI18N
        btnUpdateStock.setText("Update Product");
        btnUpdateStock.setBorder(null);
        btnUpdateStock.setBorderPainted(false);
        btnUpdateStock.setContentAreaFilled(false);
        btnUpdateStock.setFocusPainted(false);
        btnUpdateStock.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnUpdateStock.setIconTextGap(5);
        btnUpdateStock.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Images/Edit1_Red.png"))); // NOI18N
        btnUpdateStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStockActionPerformed(evt);
            }
        });

        btnViewStock.setBackground(new java.awt.Color(40, 40, 40));
        btnViewStock.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnViewStock.setForeground(new java.awt.Color(255, 255, 255));
        btnViewStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Images/View.png"))); // NOI18N
        btnViewStock.setText("View Stock");
        btnViewStock.setBorder(null);
        btnViewStock.setBorderPainted(false);
        btnViewStock.setContentAreaFilled(false);
        btnViewStock.setFocusPainted(false);
        btnViewStock.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnViewStock.setIconTextGap(40);
        btnViewStock.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Images/View_Red.png"))); // NOI18N
        btnViewStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStockActionPerformed(evt);
            }
        });

        btnAddStock.setBackground(new java.awt.Color(204, 0, 0));
        btnAddStock.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnAddStock.setForeground(new java.awt.Color(255, 255, 255));
        btnAddStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Images/Add1.png"))); // NOI18N
        btnAddStock.setText("Add Stock");
        btnAddStock.setBorder(null);
        btnAddStock.setBorderPainted(false);
        btnAddStock.setContentAreaFilled(false);
        btnAddStock.setFocusPainted(false);
        btnAddStock.setIconTextGap(50);
        btnAddStock.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Images/Add1_Red.png"))); // NOI18N
        btnAddStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStockActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(204, 0, 0));
        btnBack.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Images/Back1.png"))); // NOI18N
        btnBack.setText("Main Dash");
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setFocusPainted(false);
        btnBack.setIconTextGap(45);
        btnBack.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Images/Back1_red.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAddProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAddStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
            .addComponent(btnUpdateStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnViewStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddStock, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btnUpdateStock, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewStock, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(693, Short.MAX_VALUE))
        );

        pnlProjectInfo.setBackground(new java.awt.Color(45, 45, 45));
        pnlProjectInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblProductInfo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblProductInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblProductInfo.setText("Product Information");

        lblProductName.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblProductName.setForeground(new java.awt.Color(255, 255, 255));
        lblProductName.setText("Product Name:");

        txtProductName.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtProductName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtDescription.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtDescription.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblDescription.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblDescription.setForeground(new java.awt.Color(255, 255, 255));
        lblDescription.setText("Description:");

        lblCategory.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblCategory.setForeground(new java.awt.Color(255, 255, 255));
        lblCategory.setText("Category:");

        lblStatus.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblStatus.setText("Status:");

        lblProductModel.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblProductModel.setForeground(new java.awt.Color(255, 255, 255));
        lblProductModel.setText("Model:");

        txtProductModel.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtProductModel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblProductCost.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblProductCost.setForeground(new java.awt.Color(255, 255, 255));
        lblProductCost.setText("Cost Price:");

        txtProductCost.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtProductCost.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblProductSale.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblProductSale.setForeground(new java.awt.Color(255, 255, 255));
        lblProductSale.setText("Sales Price:");

        txtProductSale.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtProductSale.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtStatus.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtStatus.setText("Available");
        txtStatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTabbedPane2.setBackground(new java.awt.Color(45, 45, 45));
        jTabbedPane2.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        pnlExistingCategory.setBackground(new java.awt.Color(45, 45, 45));

        cmbCategory.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnlExistingCategoryLayout = new javax.swing.GroupLayout(pnlExistingCategory);
        pnlExistingCategory.setLayout(pnlExistingCategoryLayout);
        pnlExistingCategoryLayout.setHorizontalGroup(
            pnlExistingCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlExistingCategoryLayout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        pnlExistingCategoryLayout.setVerticalGroup(
            pnlExistingCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlExistingCategoryLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Existing", pnlExistingCategory);

        pnlNewCategory.setBackground(new java.awt.Color(45, 45, 45));

        txtCategory.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtCategory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNewCategoryLayout = new javax.swing.GroupLayout(pnlNewCategory);
        pnlNewCategory.setLayout(pnlNewCategoryLayout);
        pnlNewCategoryLayout.setHorizontalGroup(
            pnlNewCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNewCategoryLayout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        pnlNewCategoryLayout.setVerticalGroup(
            pnlNewCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNewCategoryLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("New", pnlNewCategory);

        javax.swing.GroupLayout pnlProjectInfoLayout = new javax.swing.GroupLayout(pnlProjectInfo);
        pnlProjectInfo.setLayout(pnlProjectInfoLayout);
        pnlProjectInfoLayout.setHorizontalGroup(
            pnlProjectInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProjectInfoLayout.createSequentialGroup()
                .addGroup(pnlProjectInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProjectInfoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblProductInfo))
                    .addGroup(pnlProjectInfoLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(pnlProjectInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlProjectInfoLayout.createSequentialGroup()
                                .addComponent(lblProductModel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtProductModel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProjectInfoLayout.createSequentialGroup()
                                .addComponent(lblDescription)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProjectInfoLayout.createSequentialGroup()
                                .addComponent(lblProductName)
                                .addGap(65, 65, 65)
                                .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlProjectInfoLayout.createSequentialGroup()
                                .addComponent(lblStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlProjectInfoLayout.createSequentialGroup()
                                .addComponent(lblProductCost)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtProductCost, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProjectInfoLayout.createSequentialGroup()
                                .addComponent(lblProductSale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtProductSale, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCategory))))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProjectInfoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        pnlProjectInfoLayout.setVerticalGroup(
            pnlProjectInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProjectInfoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblProductInfo)
                .addGap(35, 35, 35)
                .addGroup(pnlProjectInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProductName)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProjectInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescription)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProjectInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlProjectInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProductModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProductModel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProjectInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProductCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProductCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProjectInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProductSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProductSale))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pnlInStock.setBackground(new java.awt.Color(45, 45, 45));
        pnlInStock.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblInStock.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblInStock.setForeground(new java.awt.Color(255, 255, 255));
        lblInStock.setText("In Stock");

        lblQuantity.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblQuantity.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantity.setText("Quanity: ");

        numQuantity.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        numQuantity.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pnlInStockLayout = new javax.swing.GroupLayout(pnlInStock);
        pnlInStock.setLayout(pnlInStockLayout);
        pnlInStockLayout.setHorizontalGroup(
            pnlInStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInStockLayout.createSequentialGroup()
                .addGroup(pnlInStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInStockLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblQuantity)
                        .addGap(83, 83, 83)
                        .addComponent(numQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInStockLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblInStock)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        pnlInStockLayout.setVerticalGroup(
            pnlInStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInStockLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblInStock)
                .addGap(37, 37, 37)
                .addGroup(pnlInStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity)
                    .addComponent(numQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnInsertProduct.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnInsertProduct.setText("Add Product");
        btnInsertProduct.setBorderPainted(false);
        btnInsertProduct.setFocusPainted(false);
        btnInsertProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlRegisterHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 1500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(pnlProjectInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(pnlInStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(515, 515, 515)
                                .addComponent(btnInsertProduct)))))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlRegisterHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlProjectInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlInStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInsertProduct)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStockActionPerformed
        frmUpdateStock updateStock = new frmUpdateStock();
        updateStock.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnUpdateStockActionPerformed

    private void btnViewStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStockActionPerformed
        frmViewStock viewStock = new frmViewStock();
        viewStock.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnViewStockActionPerformed

    public Product productToAdd;
    private void btnInsertProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertProductActionPerformed
        //Variable decleration
        String pName, pDescription, pStatus, pCategory, pModel;
        int pQuantity;
        LocalDate local = LocalDate.now();
        Date date = Date.valueOf(local);
        double costPrice, salePrice;
        
        Validation validation = new Validation();
        Category category;
        Model model;
        //Assigning variables values            
        try 
        {
            if(!"".equals(txtProductName.getText()))
            {
                pName =  txtProductName.getText();
                lblProductName.setForeground(Color.white);
                if(!"".equals(txtDescription.getText()))
                {
                    pDescription = txtDescription.getText();
                    lblDescription.setForeground(Color.white);
                    
                    if((Integer)numQuantity.getValue() >= 0)
                    {
                        pQuantity = (Integer)numQuantity.getValue();
                        lblQuantity.setForeground(Color.white);
                        
                        if(pQuantity == 0)
                        {
                            txtStatus.setText("Not Available");
                        }
                        pStatus = txtStatus.getText();
                        if(txtProductModel.getText() != "")
                        {
                             pModel = txtProductModel.getText();
                             lblProductModel.setForeground(Color.white);
                             if(validation.testDouble(txtProductCost.getText()))
                             {
                                 costPrice = (Double)Double.parseDouble(txtProductCost.getText());
                                 lblProductCost.setForeground(Color.white);
                                 if(validation.testDouble(txtProductSale.getText()))
                                 {
                                     salePrice = (Double)Double.parseDouble(txtProductSale.getText());
                                     lblProductSale.setForeground(Color.white);
                                     
                                     int selectedCategOption = jTabbedPane2.getSelectedIndex();
                                     if(selectedCategOption == 0)
                                     {
                                         pCategory = cmbCategory.getSelectedItem().toString();
                                         category = new Category(pCategory);
                                         
                                         model = new Model(pModel);                            
                                         if(model.insert() != -1)
                                         {
                                            productToAdd = new Product(pName, pDescription, category, pStatus, model, costPrice, salePrice, date); 
                                            Stock stock = new Stock(productToAdd,pQuantity);
                                            if((productToAdd.insert() != -1)&&(category.insert() != -1))
                                            {
                                                if(stock.insert() != -1)
                                                {
                                                    JOptionPane.showMessageDialog(null, "The product was successfully registered","Registration Successful",JOptionPane.INFORMATION_MESSAGE);
                                        
                                                    AdministratorMainDash mainDash = new AdministratorMainDash();
                                                    mainDash.setVisible(true);
                                                    this.setVisible(false);
                                                }
                                                else
                                                {
                                                    JOptionPane.showMessageDialog(null, "Something went wrong during the registration process. Product Registration was unsuccessful!","Registration Failed",JOptionPane.WARNING_MESSAGE);
                                                }
                                            }
                                            
                                         }
                                         
                                     }
                                     else if(selectedCategOption == 1)
                                     {
                                         pCategory = txtCategory.getText(); 
                                         category = new Category(pCategory);
                                         
                                         
                                         if(category.insert() != -1)
                                         {
                                            model = new Model(pModel);
                                            if(model.insert() != -1)
                                            {
                                                productToAdd = new Product(pName, pDescription, category, pStatus, model, costPrice, salePrice, date); 
                                                Stock stock = new Stock(productToAdd,pQuantity);
                                                if((productToAdd.insert() != -1))
                                                {
                                                    if(stock.insert() != -1)
                                                    {
                                                        JOptionPane.showMessageDialog(null, "The product was successfully registered","Registration Successful",JOptionPane.INFORMATION_MESSAGE);
                                        
                                                        AdministratorMainDash mainDash = new AdministratorMainDash();
                                                        mainDash.setVisible(true);
                                                        this.setVisible(false);
                                                    }
                                                    else
                                                    {
                                                        JOptionPane.showMessageDialog(null, "Something went wrong during the registration process. Product Registration was unsuccessful!","Registration Failed",JOptionPane.WARNING_MESSAGE);
                                                    }
                                                }
                                                
                                            }
                                            
                                         }
                                         
                                     }
                                     
                                 }
                                 else
                                 {
                                    JOptionPane.showMessageDialog(null, "This field must be in the form of a currency!","Incorrect Product Sale Price",JOptionPane.WARNING_MESSAGE);
                                    txtProductSale.setText("");
                                    txtProductSale.grabFocus();
                                    lblProductSale.setForeground(Color.red);
                                 }
                             }
                             else
                             {
                                JOptionPane.showMessageDialog(null, "This field must be in the form of a currency!","Incorrect Product Cost Price",JOptionPane.WARNING_MESSAGE);
                                txtProductCost.setText("");
                                txtProductCost.grabFocus();
                                lblProductCost.setForeground(Color.red);
                             }
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "This field cannot be empty. Please Try Again!","Incorrect Product Model",JOptionPane.WARNING_MESSAGE);
                            txtProductModel.setText("");
                            txtProductModel.grabFocus();
                            lblProductModel.setForeground(Color.red);
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Quantity cannot be negative!","Incorrect Quantity",JOptionPane.WARNING_MESSAGE);
                        lblQuantity.setForeground(Color.red);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "This field cannot be empty. Please Try Again!","Incorrect Product Description",JOptionPane.WARNING_MESSAGE);
                    txtDescription.setText("");
                    txtDescription.grabFocus();
                    lblDescription.setForeground(Color.red);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "This field cannot be empty. Please Try Again!","Incorrect Product Name",JOptionPane.WARNING_MESSAGE);
                txtProductName.setText("");
                txtProductName.grabFocus();
                lblProductName.setForeground(Color.red);
            }
        } catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnInsertProductActionPerformed

    private void btnAddStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStockActionPerformed
        frmAddStock addStock = new frmAddStock();
        addStock.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddStockActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        AdministratorMainDash mainDash = new AdministratorMainDash();
        mainDash.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoryActionPerformed

    }//GEN-LAST:event_txtCategoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAddProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnAddStock;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnInsertProduct;
    private javax.swing.JButton btnUpdateStock;
    private javax.swing.JButton btnViewStock;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblAddProduct;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblInStock;
    private javax.swing.JLabel lblProductCost;
    private javax.swing.JLabel lblProductInfo;
    private javax.swing.JLabel lblProductModel;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblProductSale;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JSpinner numQuantity;
    private javax.swing.JPanel pnlExistingCategory;
    private javax.swing.JPanel pnlInStock;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlNewCategory;
    private javax.swing.JPanel pnlProjectInfo;
    private javax.swing.JPanel pnlRegisterHeader;
    private javax.swing.JPanel pnlRegisterHeader1;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtProductCost;
    private javax.swing.JTextField txtProductModel;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtProductSale;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
