/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import PersonManagement.PersonManagement_Methods;
import PersonManagement.User;
import ProductManagement.Order;
import ProductManagement.OrderItems;
import ProductManagement.ProductManagement_Methods;
import bc_stationary_bll.Communication;
import bc_stationary_bll.Email;
import bc_stationary_bll.Reports.ReportBuilder;
import bc_stationary_bll.Reports.ReportMenu;
import bc_stationary_bll.Reports.Reporting;
import bc_stationary_management_system.ClientHandler;
import java.awt.Color;
import java.awt.Cursor;
import java.io.IOException;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Eldane
 */
public class frmEditOrders extends javax.swing.JFrame {

    /**
     * Creates new form frmEditOrders
     */
    public ArrayList<User> users;
    Communication c;
    public frmEditOrders() {
        try {
            initComponents();
            this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
            this.getContentPane().setBackground(new Color(45, 45, 45));
            
            Order order = new Order();
            c = new Communication(ProductManagement_Methods.ORDER_SELECTUSERS_WITH_OPEN_ORDERS.methodIdentifier, order);
            users = new ClientHandler(c).request().listResult;
            cmbUsers.addItem("Select a User");
            for(User u:users){
                cmbUsers.addItem(u.toString());
            }
        } catch (IOException ex) {
            Logger.getLogger(frmEditOrders.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainDashHeader = new javax.swing.JPanel();
        pnlRegisterHeader1 = new javax.swing.JPanel();
        lblAddRequest = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        btnAddRequest = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        cmbUsers = new javax.swing.JComboBox<>();
        lblSearchUsers = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbxOrders = new javax.swing.JList<>();
        pnlProjectInfo = new javax.swing.JPanel();
        lblProductInfo = new javax.swing.JLabel();
        btnFinalizeOrder = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lbxOrderInfo = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlMainDashHeader.setBackground(new java.awt.Color(255, 255, 0));
        pnlMainDashHeader.setPreferredSize(new java.awt.Dimension(1071, 530));

        pnlRegisterHeader1.setBackground(new java.awt.Color(204, 0, 0));
        pnlRegisterHeader1.setPreferredSize(new java.awt.Dimension(1307, 65));

        lblAddRequest.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblAddRequest.setForeground(new java.awt.Color(255, 255, 255));
        lblAddRequest.setText("Finalize Order");
        lblAddRequest.setAlignmentY(0.0F);

        javax.swing.GroupLayout pnlRegisterHeader1Layout = new javax.swing.GroupLayout(pnlRegisterHeader1);
        pnlRegisterHeader1.setLayout(pnlRegisterHeader1Layout);
        pnlRegisterHeader1Layout.setHorizontalGroup(
            pnlRegisterHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterHeader1Layout.createSequentialGroup()
                .addGap(607, 607, 607)
                .addComponent(lblAddRequest)
                .addContainerGap(733, Short.MAX_VALUE))
        );
        pnlRegisterHeader1Layout.setVerticalGroup(
            pnlRegisterHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterHeader1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAddRequest)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlMainDashHeaderLayout = new javax.swing.GroupLayout(pnlMainDashHeader);
        pnlMainDashHeader.setLayout(pnlMainDashHeaderLayout);
        pnlMainDashHeaderLayout.setHorizontalGroup(
            pnlMainDashHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegisterHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, 1500, Short.MAX_VALUE)
        );
        pnlMainDashHeaderLayout.setVerticalGroup(
            pnlMainDashHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainDashHeaderLayout.createSequentialGroup()
                .addComponent(pnlRegisterHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMenu.setBackground(new java.awt.Color(40, 40, 40));

        btnAddRequest.setBackground(new java.awt.Color(204, 0, 0));
        btnAddRequest.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnAddRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnAddRequest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Images/Edit1_Red.png"))); // NOI18N
        btnAddRequest.setBorder(null);
        btnAddRequest.setBorderPainted(false);
        btnAddRequest.setContentAreaFilled(false);
        btnAddRequest.setFocusPainted(false);
        btnAddRequest.setIconTextGap(10);
        btnAddRequest.setLabel("Finalize Orders");
        btnAddRequest.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Images/Edit1_Red.png"))); // NOI18N

        btnBack.setBackground(new java.awt.Color(204, 0, 0));
        btnBack.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Images/Back1.png"))); // NOI18N
        btnBack.setText("Main Dash");
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setFocusPainted(false);
        btnBack.setIconTextGap(36);
        btnBack.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Images/Back1_red.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(btnAddRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(862, Short.MAX_VALUE))
        );

        cmbUsers.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        cmbUsers.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbUsersPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        lblSearchUsers.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblSearchUsers.setForeground(new java.awt.Color(255, 255, 255));
        lblSearchUsers.setText("Select an Order to view items:");

        lbxOrders.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lbxOrders.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lbxOrdersValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lbxOrders);

        pnlProjectInfo.setBackground(new java.awt.Color(45, 45, 45));
        pnlProjectInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblProductInfo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblProductInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblProductInfo.setText("Order Information");

        btnFinalizeOrder.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnFinalizeOrder.setText("Finalize Order");
        btnFinalizeOrder.setBorderPainted(false);
        btnFinalizeOrder.setFocusPainted(false);
        btnFinalizeOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinalizeOrderMouseClicked(evt);
            }
        });

        lbxOrderInfo.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lbxOrderInfo.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lbxOrderInfoValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lbxOrderInfo);

        javax.swing.GroupLayout pnlProjectInfoLayout = new javax.swing.GroupLayout(pnlProjectInfo);
        pnlProjectInfo.setLayout(pnlProjectInfoLayout);
        pnlProjectInfoLayout.setHorizontalGroup(
            pnlProjectInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProjectInfoLayout.createSequentialGroup()
                .addGroup(pnlProjectInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProjectInfoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblProductInfo))
                    .addGroup(pnlProjectInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlProjectInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnFinalizeOrder)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlProjectInfoLayout.setVerticalGroup(
            pnlProjectInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProjectInfoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblProductInfo)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFinalizeOrder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMainDashHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 1500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbUsers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSearchUsers))
                        .addGap(38, 38, 38)
                        .addComponent(pnlProjectInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMainDashHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlProjectInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblSearchUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        AdministratorMainDash mainDash = new AdministratorMainDash();
        mainDash.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed
    
    ArrayList<Order> userOrders;
    private void cmbUsersPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbUsersPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        User selectedUser = null;
        if(cmbUsers.getSelectedIndex()> 0){
            try {
                for(User u: users)
                {
                    if(cmbUsers.getSelectedItem().toString().equals(u.toString())){
                        selectedUser = u;
                    }
                }
                
                Order order  = new Order(selectedUser,null,null,null);
                c = new Communication(ProductManagement_Methods.ORDER_SELECT_USER.methodIdentifier, order);
                userOrders = new ClientHandler(c).request().listResult;
                
                DefaultListModel model = new DefaultListModel();
                for(Order o: userOrders){
                    model.addElement(o.toString());
                }
                lbxOrders.setModel(model);
            } catch (IOException ex) {
                Logger.getLogger(frmEditOrders.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       
    }//GEN-LAST:event_cmbUsersPopupMenuWillBecomeInvisible
    public Order selectedOrder;
    private void lbxOrdersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lbxOrdersValueChanged
        if(lbxOrders.getSelectedIndex()>-1){
            int index = lbxOrders.getSelectedIndex();
            selectedOrder= userOrders.get(index);
            
            DefaultListModel model = new DefaultListModel();
            for(OrderItems oi: selectedOrder.getOrderItems()){
                model.addElement(oi.toString());
            }
            lbxOrderInfo.setModel(model);
        }
    }//GEN-LAST:event_lbxOrdersValueChanged

    private void btnFinalizeOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinalizeOrderMouseClicked
        if(lbxOrders.getSelectedIndex()>-1){
            try {
                btnFinalizeOrder.setEnabled(false);
                
                LocalDate localOrder = LocalDate.now();
                Date receiveDate = Date.valueOf(localOrder);
                ArrayList<OrderItems> items = selectedOrder.getOrderItems();
                String user = cmbUsers.getSelectedItem().toString();
                selectedOrder.setReceivedDate(receiveDate);
                c = new Communication(ProductManagement_Methods.ORDER_UPDATE.methodIdentifier, selectedOrder);
                int orderUpdateSuccess = new ClientHandler(c).request().intResult;
                
                this.setCursor(Cursor.getPredefinedCursor(WAIT_CURSOR));
                if(orderUpdateSuccess != -1)
                {
                    Reporting report = new ReportBuilder(ReportMenu.ORDER_DELIVERY_REPORT.reportOption,items).createReport();
                    report.generateReport();
                    String message = String.format("Dear %S,\n Your order is ready for delivery and will arrive shortly!\nPlease find attached, to this mail, the list of items that are currently in this order.", user);
                    String path = "C:\\Users\\Eldane\\Documents\\NetBeansProjects\\BC_Stationary_Management_System\\"+report.docName;
                    Email email = new Email("eldanefer1@gmail.com", message, "Your Order is Ready for Delivery", path);
                    email.sendEmail();
                    
                    this.setCursor(Cursor.getDefaultCursor());
                    JOptionPane.showMessageDialog(null, "Order was successfully finalized! It is now ready for delivery.","Successful Finalization",JOptionPane.INFORMATION_MESSAGE);
                    AdministratorMainDash mainDash = new AdministratorMainDash();
                    mainDash.setVisible(true);
                    this.setVisible(false);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Order could not be finalized. Please try again later.","Failure!",JOptionPane.WARNING_MESSAGE);
                }
            } catch (IOException ex) {
                Logger.getLogger(frmEditOrders.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnFinalizeOrderMouseClicked

    private void lbxOrderInfoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lbxOrderInfoValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lbxOrderInfoValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEditOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEditOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEditOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEditOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEditOrders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRequest;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFinalizeOrder;
    private javax.swing.JComboBox<String> cmbUsers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAddRequest;
    private javax.swing.JLabel lblProductInfo;
    private javax.swing.JLabel lblSearchUsers;
    private javax.swing.JList<String> lbxOrderInfo;
    private javax.swing.JList<String> lbxOrders;
    private javax.swing.JPanel pnlMainDashHeader;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlProjectInfo;
    private javax.swing.JPanel pnlRegisterHeader1;
    // End of variables declaration//GEN-END:variables
}
