/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import PersonManagement.*;
import Validation.InputValidation;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author Eldane
 */
public class frmRegisterUser extends javax.swing.JFrame {

    /**
     * Creates new form frmRegisterUser
     */
    public frmRegisterUser() {
        initComponents();
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        this.getContentPane().setBackground(new Color(45,45,45));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegisterHeader = new javax.swing.JPanel();
        pnlRegisterHeader1 = new javax.swing.JPanel();
        lblRegisterUser = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        btnRegisterUser = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        pnlPersonalInfo = new javax.swing.JPanel();
        lblPersonalInfo = new javax.swing.JLabel();
        lblFirstname = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        lblLastname = new javax.swing.JLabel();
        lblCampus = new javax.swing.JLabel();
        cmbCampus = new javax.swing.JComboBox<>();
        lblIDNumber = new javax.swing.JLabel();
        txtIDNumber = new javax.swing.JTextField();
        pnlAddressInfo = new javax.swing.JPanel();
        lblAddressInfo = new javax.swing.JLabel();
        lblLine1 = new javax.swing.JLabel();
        txtLine1 = new javax.swing.JTextField();
        txtLine2 = new javax.swing.JTextField();
        lblLine2 = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblPostalCode = new javax.swing.JLabel();
        txtPostalCode = new javax.swing.JTextField();
        pnlContactInfo = new javax.swing.JPanel();
        lblContactInfo = new javax.swing.JLabel();
        lblCellNo = new javax.swing.JLabel();
        txtCellphoneNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        btnNextRegistration = new javax.swing.JButton();
        pnlDepartmentInfo = new javax.swing.JPanel();
        lblDepartmentInfo = new javax.swing.JLabel();
        lblDepartment = new javax.swing.JLabel();
        cmbDepartment = new javax.swing.JComboBox<>();
        cbxNewDepartment = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(45, 45, 45));
        setResizable(false);

        pnlRegisterHeader.setBackground(new java.awt.Color(255, 255, 0));
        pnlRegisterHeader.setPreferredSize(new java.awt.Dimension(1071, 530));

        pnlRegisterHeader1.setBackground(new java.awt.Color(204, 0, 0));
        pnlRegisterHeader1.setPreferredSize(new java.awt.Dimension(1307, 65));

        lblRegisterUser.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblRegisterUser.setForeground(new java.awt.Color(255, 255, 255));
        lblRegisterUser.setText("Register User");
        lblRegisterUser.setAlignmentY(0.0F);

        javax.swing.GroupLayout pnlRegisterHeader1Layout = new javax.swing.GroupLayout(pnlRegisterHeader1);
        pnlRegisterHeader1.setLayout(pnlRegisterHeader1Layout);
        pnlRegisterHeader1Layout.setHorizontalGroup(
            pnlRegisterHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterHeader1Layout.createSequentialGroup()
                .addGap(607, 607, 607)
                .addComponent(lblRegisterUser)
                .addContainerGap(745, Short.MAX_VALUE))
        );
        pnlRegisterHeader1Layout.setVerticalGroup(
            pnlRegisterHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterHeader1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lblRegisterUser)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlRegisterHeaderLayout = new javax.swing.GroupLayout(pnlRegisterHeader);
        pnlRegisterHeader.setLayout(pnlRegisterHeaderLayout);
        pnlRegisterHeaderLayout.setHorizontalGroup(
            pnlRegisterHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegisterHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, 1500, Short.MAX_VALUE)
        );
        pnlRegisterHeaderLayout.setVerticalGroup(
            pnlRegisterHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterHeaderLayout.createSequentialGroup()
                .addComponent(pnlRegisterHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMenu.setBackground(new java.awt.Color(40, 40, 40));

        btnRegisterUser.setBackground(new java.awt.Color(204, 0, 0));
        btnRegisterUser.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnRegisterUser.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Images/Add1_Red.png"))); // NOI18N
        btnRegisterUser.setText("Register User");
        btnRegisterUser.setBorder(null);
        btnRegisterUser.setBorderPainted(false);
        btnRegisterUser.setContentAreaFilled(false);
        btnRegisterUser.setFocusPainted(false);
        btnRegisterUser.setIconTextGap(10);
        btnRegisterUser.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Images/Add1_Red.png"))); // NOI18N

        btnBack.setBackground(new java.awt.Color(40, 40, 40));
        btnBack.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Images/Back1.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setFocusPainted(false);
        btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnBack.setIconTextGap(70);
        btnBack.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Images/Back1_red.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegisterUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btnRegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(814, Short.MAX_VALUE))
        );

        btnRegisterUser.getAccessibleContext().setAccessibleDescription("");

        pnlPersonalInfo.setBackground(new java.awt.Color(45, 45, 45));
        pnlPersonalInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblPersonalInfo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblPersonalInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblPersonalInfo.setText("Personal Information");

        lblFirstname.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblFirstname.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstname.setText("Firstname:");

        txtFirstname.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtFirstname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtLastname.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtLastname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblLastname.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblLastname.setForeground(new java.awt.Color(255, 255, 255));
        lblLastname.setText("Lastname:");

        lblCampus.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblCampus.setForeground(new java.awt.Color(255, 255, 255));
        lblCampus.setText("Campus:");

        cmbCampus.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        cmbCampus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pretoria" }));

        lblIDNumber.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblIDNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblIDNumber.setText("ID Number:");

        txtIDNumber.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtIDNumber.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pnlPersonalInfoLayout = new javax.swing.GroupLayout(pnlPersonalInfo);
        pnlPersonalInfo.setLayout(pnlPersonalInfoLayout);
        pnlPersonalInfoLayout.setHorizontalGroup(
            pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblPersonalInfo))
                    .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                                .addComponent(lblCampus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbCampus, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                                    .addComponent(lblIDNumber)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtIDNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                                        .addComponent(lblLastname)
                                        .addGap(63, 63, 63)
                                        .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                                        .addComponent(lblFirstname)
                                        .addGap(65, 65, 65)
                                        .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        pnlPersonalInfoLayout.setVerticalGroup(
            pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblPersonalInfo)
                .addGap(35, 35, 35)
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstname)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastname)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIDNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampus)
                    .addComponent(cmbCampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        pnlAddressInfo.setBackground(new java.awt.Color(45, 45, 45));
        pnlAddressInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblAddressInfo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblAddressInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblAddressInfo.setText("Address Information");

        lblLine1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblLine1.setForeground(new java.awt.Color(255, 255, 255));
        lblLine1.setText("Line 1:");

        txtLine1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtLine1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtLine2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtLine2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblLine2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblLine2.setForeground(new java.awt.Color(255, 255, 255));
        lblLine2.setText("Line 2:");

        lblCity.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblCity.setForeground(new java.awt.Color(255, 255, 255));
        lblCity.setText("City:");

        txtCity.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtCity.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblPostalCode.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblPostalCode.setForeground(new java.awt.Color(255, 255, 255));
        lblPostalCode.setText("Postal Code:");

        txtPostalCode.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtPostalCode.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pnlAddressInfoLayout = new javax.swing.GroupLayout(pnlAddressInfo);
        pnlAddressInfo.setLayout(pnlAddressInfoLayout);
        pnlAddressInfoLayout.setHorizontalGroup(
            pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddressInfoLayout.createSequentialGroup()
                .addGroup(pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddressInfoLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlAddressInfoLayout.createSequentialGroup()
                                .addComponent(lblLine1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlAddressInfoLayout.createSequentialGroup()
                                .addGroup(pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLine2)
                                    .addComponent(lblCity)
                                    .addComponent(lblPostalCode))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addGroup(pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(pnlAddressInfoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblAddressInfo)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pnlAddressInfoLayout.setVerticalGroup(
            pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddressInfoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblAddressInfo)
                .addGap(35, 35, 35)
                .addGroup(pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLine1)
                    .addComponent(txtLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLine2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPostalCode)
                    .addComponent(txtPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pnlContactInfo.setBackground(new java.awt.Color(45, 45, 45));
        pnlContactInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblContactInfo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblContactInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblContactInfo.setText("Contact Information");

        lblCellNo.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblCellNo.setForeground(new java.awt.Color(255, 255, 255));
        lblCellNo.setText("Cellphone No:");

        txtCellphoneNo.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtCellphoneNo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtEmail.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblEmail.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email:");

        javax.swing.GroupLayout pnlContactInfoLayout = new javax.swing.GroupLayout(pnlContactInfo);
        pnlContactInfo.setLayout(pnlContactInfoLayout);
        pnlContactInfoLayout.setHorizontalGroup(
            pnlContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContactInfoLayout.createSequentialGroup()
                .addGroup(pnlContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContactInfoLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(pnlContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContactInfoLayout.createSequentialGroup()
                                .addComponent(lblCellNo)
                                .addGap(54, 54, 54))
                            .addGroup(pnlContactInfoLayout.createSequentialGroup()
                                .addComponent(lblEmail)
                                .addGap(119, 119, 119)))
                        .addGroup(pnlContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(txtCellphoneNo)))
                    .addGroup(pnlContactInfoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblContactInfo)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        pnlContactInfoLayout.setVerticalGroup(
            pnlContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContactInfoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblContactInfo)
                .addGap(35, 35, 35)
                .addGroup(pnlContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCellNo)
                    .addComponent(txtCellphoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnlContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        btnNextRegistration.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnNextRegistration.setText("Next");
        btnNextRegistration.setFocusPainted(false);
        btnNextRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextRegistrationActionPerformed(evt);
            }
        });

        pnlDepartmentInfo.setBackground(new java.awt.Color(45, 45, 45));
        pnlDepartmentInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDepartmentInfo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblDepartmentInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblDepartmentInfo.setText("Department Information");

        lblDepartment.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblDepartment.setForeground(new java.awt.Color(255, 255, 255));
        lblDepartment.setText("Department");

        cmbDepartment.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        cbxNewDepartment.setBackground(new java.awt.Color(45, 45, 45));
        cbxNewDepartment.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cbxNewDepartment.setForeground(new java.awt.Color(255, 255, 255));
        cbxNewDepartment.setText("New Department");
        cbxNewDepartment.setFocusPainted(false);

        javax.swing.GroupLayout pnlDepartmentInfoLayout = new javax.swing.GroupLayout(pnlDepartmentInfo);
        pnlDepartmentInfo.setLayout(pnlDepartmentInfoLayout);
        pnlDepartmentInfoLayout.setHorizontalGroup(
            pnlDepartmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDepartmentInfoLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblDepartment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(pnlDepartmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxNewDepartment)
                    .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
            .addGroup(pnlDepartmentInfoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblDepartmentInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDepartmentInfoLayout.setVerticalGroup(
            pnlDepartmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDepartmentInfoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblDepartmentInfo)
                .addGap(32, 32, 32)
                .addGroup(pnlDepartmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartment)
                    .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxNewDepartment)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlRegisterHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 1500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 160, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlPersonalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(pnlContactInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addComponent(pnlDepartmentInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(236, 236, 236))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlAddressInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165)
                        .addComponent(btnNextRegistration)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlRegisterHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNextRegistration)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlContactInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlPersonalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlDepartmentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlAddressInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public dataClass dataClass = new dataClass();
            
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        frmLogin login = new frmLogin();
        login.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextRegistrationActionPerformed

        //Variable Declaration
        String userFirstName, userLastName, userCampus, addressLine1, addressLine2, addressCity, contactCell, contactEmail, userID, userDepart;
        int addressPostal;
        InputValidation inValidation = new InputValidation();
        
        try 
        {
            //Assigning values to variables
            userFirstName = (String)txtFirstname.getText();
            userLastName = (String)txtLastname.getText();
            userCampus = (String)cmbCampus.getSelectedItem().toString();
            addressLine1 = (String)txtLine1.getText();
            addressLine2 = (String)txtLine2.getText();
            addressCity = (String)txtCity.getText();
            addressPostal = (Integer)Integer.parseInt(txtPostalCode.getText());
            contactCell =  (String)txtCellphoneNo.getText();
            contactEmail = (String)txtEmail.getText();
            userID = (String)txtIDNumber.getText();
            userDepart = (String)cmbDepartment.getSelectedItem().toString();
            
            //Creating and populating arrays to pass values to validation class
            String[][] nameVariables = {{"First Name",userFirstName},
                {"Last Name",userLastName}};
            
            String[][] stringVariables = {{"Campus",userCampus},
                {"City",addressCity},{"Department",userDepart}};
            
            String[][] stringWithIntVariables = {{"Address Line 1",addressLine1},
                {"Address Line 2",addressLine2},};
            
            String[][] idString = {{"ID Number",userID}};
            
            Object[][] intVariables = {{"Postal Code",addressPostal}};
            
            Object[][] cellVariables = {{"Cellphone Number",contactCell}};
            
            Object[][] emailVariables = {{"Email Address",contactEmail}};
            
            //Passing arrays to validation class            
            try 
            {
                inValidation.validateName_Surname(nameVariables);
                inValidation.validateString(stringVariables);
                inValidation.validateStringInt(stringWithIntVariables);
                inValidation.validateInt(intVariables);
                inValidation.validateCell(cellVariables);
                inValidation.validateEmail(emailVariables);
                inValidation.validateID(idString);
            }
            catch (Exception e) 
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            finally
            {
                dataClass.setUserFirstName(userFirstName);
                dataClass.setUserLastName(userLastName);
                dataClass.setUserID(userID);
                dataClass.setUserCampus(userCampus);
                dataClass.setUserDept(userDepart);
                dataClass.setContactCell(contactCell);
                dataClass.setContactEmail(contactEmail);
                dataClass.setAddressLine1(addressLine1);
                dataClass.setAddressLine2(addressLine2);
                dataClass.setAddressCity(addressCity);
                dataClass.setAddressPostal(addressPostal);
            }
        } 
        catch (Exception e) 
        {
            
        }
        
        frmRegisterUserLogin userLogin = new frmRegisterUserLogin();
        userLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnNextRegistrationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegisterUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNextRegistration;
    private javax.swing.JButton btnRegisterUser;
    private javax.swing.JCheckBox cbxNewDepartment;
    private javax.swing.JComboBox<String> cmbCampus;
    private javax.swing.JComboBox<String> cmbDepartment;
    private javax.swing.JLabel lblAddressInfo;
    private javax.swing.JLabel lblCampus;
    private javax.swing.JLabel lblCellNo;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblContactInfo;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblDepartmentInfo;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblIDNumber;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblLine1;
    private javax.swing.JLabel lblLine2;
    private javax.swing.JLabel lblPersonalInfo;
    private javax.swing.JLabel lblPostalCode;
    private javax.swing.JLabel lblRegisterUser;
    private javax.swing.JPanel pnlAddressInfo;
    private javax.swing.JPanel pnlContactInfo;
    private javax.swing.JPanel pnlDepartmentInfo;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPersonalInfo;
    private javax.swing.JPanel pnlRegisterHeader;
    private javax.swing.JPanel pnlRegisterHeader1;
    private javax.swing.JTextField txtCellphoneNo;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtIDNumber;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtLine1;
    private javax.swing.JTextField txtLine2;
    private javax.swing.JTextField txtPostalCode;
    // End of variables declaration//GEN-END:variables
}
