/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import PersonManagement.SecurityQuestions;
import PersonManagement.User;
import PersonManagement.*;
import bc_stationary_bll.Validation;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Eldane
 */
public class frmUpdateUser extends javax.swing.JFrame {

    /**
     * Creates new form frmUpdateUser
     */
    public ArrayList<User> userList;

    public frmUpdateUser() {
        initComponents();
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        this.getContentPane().setBackground(new Color(45, 45, 45));

        User user = new User();
        userList = user.select();

        DefaultListModel model = new DefaultListModel();
        // Populate Listbox
        for (User u : userList) {
            model.addElement(u);
        }

        lbxUsers.setModel(model);

        ArrayList<Department> departments = new ArrayList<Department>();
        Department dept = new Department();
        departments = dept.select();
        for (Department d : departments) {
            cmbDepartment.addItem(d.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegisterHeader = new javax.swing.JPanel();
        pnlRegisterHeader1 = new javax.swing.JPanel();
        lblUpdateUser = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        btnViewUser = new javax.swing.JButton();
        btnAddUser = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnUpdateUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbxUsers = new javax.swing.JList<>();
        pnlUserInfo1 = new javax.swing.JPanel();
        lblUserInfoUpdate = new javax.swing.JLabel();
        lblFirstnameUpdate = new javax.swing.JLabel();
        txtFirstnameUpdate = new javax.swing.JTextField();
        lblLastnameUpdate = new javax.swing.JLabel();
        txtLastnameUpdate = new javax.swing.JTextField();
        lblCampusUpdate = new javax.swing.JLabel();
        pnlLoginInfo1 = new javax.swing.JPanel();
        lblLoginInfo1 = new javax.swing.JLabel();
        lblUsername1 = new javax.swing.JLabel();
        txtUsername1 = new javax.swing.JTextField();
        lblAccessLevel1 = new javax.swing.JLabel();
        lblStatus1 = new javax.swing.JLabel();
        btnEditUser = new javax.swing.JButton();
        cmbStatus = new javax.swing.JComboBox<>();
        cmbAccessLevel = new javax.swing.JComboBox<>();
        pnlDepartmentInfo = new javax.swing.JPanel();
        lblDepartmentInfo = new javax.swing.JLabel();
        cmbDepartment = new javax.swing.JComboBox<>();
        lblDepartment = new javax.swing.JLabel();
        pnlAddressInfo = new javax.swing.JPanel();
        lblAddressInfo = new javax.swing.JLabel();
        lblLine1 = new javax.swing.JLabel();
        txtLine1 = new javax.swing.JTextField();
        txtLine2 = new javax.swing.JTextField();
        lblLine2 = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblPostalCode = new javax.swing.JLabel();
        txtPostalCode = new javax.swing.JTextField();
        lblCellNo = new javax.swing.JLabel();
        txtCellphoneNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblIDNumber = new javax.swing.JLabel();
        txtIDNumber = new javax.swing.JTextField();
        cmbCampus = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlRegisterHeader.setBackground(new java.awt.Color(255, 255, 0));
        pnlRegisterHeader.setPreferredSize(new java.awt.Dimension(1071, 530));

        pnlRegisterHeader1.setBackground(new java.awt.Color(204, 0, 0));
        pnlRegisterHeader1.setPreferredSize(new java.awt.Dimension(1307, 65));

        lblUpdateUser.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblUpdateUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdateUser.setText("Update User");
        lblUpdateUser.setAlignmentY(0.0F);

        javax.swing.GroupLayout pnlRegisterHeader1Layout = new javax.swing.GroupLayout(pnlRegisterHeader1);
        pnlRegisterHeader1.setLayout(pnlRegisterHeader1Layout);
        pnlRegisterHeader1Layout.setHorizontalGroup(
            pnlRegisterHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterHeader1Layout.createSequentialGroup()
                .addGap(607, 607, 607)
                .addComponent(lblUpdateUser)
                .addContainerGap(752, Short.MAX_VALUE))
        );
        pnlRegisterHeader1Layout.setVerticalGroup(
            pnlRegisterHeader1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterHeader1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(lblUpdateUser)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlRegisterHeaderLayout = new javax.swing.GroupLayout(pnlRegisterHeader);
        pnlRegisterHeader.setLayout(pnlRegisterHeaderLayout);
        pnlRegisterHeaderLayout.setHorizontalGroup(
            pnlRegisterHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegisterHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, 1500, Short.MAX_VALUE)
        );
        pnlRegisterHeaderLayout.setVerticalGroup(
            pnlRegisterHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterHeaderLayout.createSequentialGroup()
                .addComponent(pnlRegisterHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMenu.setBackground(new java.awt.Color(40, 40, 40));

        btnViewUser.setBackground(new java.awt.Color(40, 40, 40));
        btnViewUser.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnViewUser.setForeground(new java.awt.Color(255, 255, 255));
        btnViewUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Images/View.png"))); // NOI18N
        btnViewUser.setText("View User");
        btnViewUser.setBorder(null);
        btnViewUser.setBorderPainted(false);
        btnViewUser.setContentAreaFilled(false);
        btnViewUser.setFocusPainted(false);
        btnViewUser.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnViewUser.setIconTextGap(25);
        btnViewUser.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Images/View_Red.png"))); // NOI18N
        btnViewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewUserActionPerformed(evt);
            }
        });

        btnAddUser.setBackground(new java.awt.Color(204, 0, 0));
        btnAddUser.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnAddUser.setForeground(new java.awt.Color(255, 255, 255));
        btnAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Images/Add1.png"))); // NOI18N
        btnAddUser.setText("Add User");
        btnAddUser.setBorder(null);
        btnAddUser.setBorderPainted(false);
        btnAddUser.setContentAreaFilled(false);
        btnAddUser.setFocusPainted(false);
        btnAddUser.setIconTextGap(30);
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(204, 0, 0));
        btnBack.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Images/Back1.png"))); // NOI18N
        btnBack.setText("Main Dash");
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setFocusPainted(false);
        btnBack.setIconTextGap(20);
        btnBack.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Images/Back1_red.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnUpdateUser.setBackground(new java.awt.Color(204, 0, 0));
        btnUpdateUser.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnUpdateUser.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Images/Edit1_Red.png"))); // NOI18N
        btnUpdateUser.setText("Update User");
        btnUpdateUser.setBorder(null);
        btnUpdateUser.setBorderPainted(false);
        btnUpdateUser.setContentAreaFilled(false);
        btnUpdateUser.setFocusPainted(false);
        btnUpdateUser.setIconTextGap(5);
        btnUpdateUser.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Images/Edit1_Red.png"))); // NOI18N

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(btnUpdateUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnViewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(747, Short.MAX_VALUE))
        );

        lbxUsers.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lbxUsers.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lbxUsersValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lbxUsers);

        pnlUserInfo1.setBackground(new java.awt.Color(45, 45, 45));
        pnlUserInfo1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblUserInfoUpdate.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblUserInfoUpdate.setForeground(new java.awt.Color(255, 255, 255));
        lblUserInfoUpdate.setText("User Information");

        lblFirstnameUpdate.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblFirstnameUpdate.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstnameUpdate.setText("Firstname:");

        txtFirstnameUpdate.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtFirstnameUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtFirstnameUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblLastnameUpdate.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblLastnameUpdate.setForeground(new java.awt.Color(255, 255, 255));
        lblLastnameUpdate.setText("Lastname:");

        txtLastnameUpdate.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtLastnameUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtLastnameUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblCampusUpdate.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblCampusUpdate.setForeground(new java.awt.Color(255, 255, 255));
        lblCampusUpdate.setText("Campus:");

        pnlLoginInfo1.setBackground(new java.awt.Color(45, 45, 45));
        pnlLoginInfo1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblLoginInfo1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblLoginInfo1.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginInfo1.setText("Login Information");

        lblUsername1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblUsername1.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername1.setText("Username:");

        txtUsername1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtUsername1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtUsername1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblAccessLevel1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblAccessLevel1.setForeground(new java.awt.Color(255, 255, 255));
        lblAccessLevel1.setText("Access Level:");

        lblStatus1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblStatus1.setForeground(new java.awt.Color(255, 255, 255));
        lblStatus1.setText("Status");

        btnEditUser.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnEditUser.setText("Update User");
        btnEditUser.setBorderPainted(false);
        btnEditUser.setFocusPainted(false);
        btnEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditUserActionPerformed(evt);
            }
        });

        cmbStatus.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Pending", "Disabled" }));

        cmbAccessLevel.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        cmbAccessLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Standard" }));

        pnlDepartmentInfo.setBackground(new java.awt.Color(45, 45, 45));
        pnlDepartmentInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDepartmentInfo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblDepartmentInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblDepartmentInfo.setText("Department Information");

        cmbDepartment.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        cmbDepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbDepartmentMouseClicked(evt);
            }
        });

        lblDepartment.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblDepartment.setForeground(new java.awt.Color(255, 255, 255));
        lblDepartment.setText("Department:");

        javax.swing.GroupLayout pnlDepartmentInfoLayout = new javax.swing.GroupLayout(pnlDepartmentInfo);
        pnlDepartmentInfo.setLayout(pnlDepartmentInfoLayout);
        pnlDepartmentInfoLayout.setHorizontalGroup(
            pnlDepartmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDepartmentInfoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblDepartmentInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDepartmentInfoLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(lblDepartment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
        pnlDepartmentInfoLayout.setVerticalGroup(
            pnlDepartmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDepartmentInfoLayout.createSequentialGroup()
                .addComponent(lblDepartmentInfo)
                .addGap(18, 18, 18)
                .addGroup(pnlDepartmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDepartment))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlLoginInfo1Layout = new javax.swing.GroupLayout(pnlLoginInfo1);
        pnlLoginInfo1.setLayout(pnlLoginInfo1Layout);
        pnlLoginInfo1Layout.setHorizontalGroup(
            pnlLoginInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginInfo1Layout.createSequentialGroup()
                .addGroup(pnlLoginInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginInfo1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlDepartmentInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlLoginInfo1Layout.createSequentialGroup()
                        .addGroup(pnlLoginInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLoginInfo1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(pnlLoginInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLoginInfo1)
                                    .addComponent(lblAccessLevel1)
                                    .addComponent(lblStatus1)
                                    .addComponent(lblUsername1)
                                    .addComponent(txtUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbAccessLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlLoginInfo1Layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(btnEditUser)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlLoginInfo1Layout.setVerticalGroup(
            pnlLoginInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginInfo1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(pnlDepartmentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLoginInfo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsername1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAccessLevel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbAccessLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblStatus1)
                .addGap(4, 4, 4)
                .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnEditUser)
                .addGap(26, 26, 26))
        );

        pnlAddressInfo.setBackground(new java.awt.Color(45, 45, 45));
        pnlAddressInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblAddressInfo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblAddressInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblAddressInfo.setText("Address & Contact Information");

        lblLine1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblLine1.setForeground(new java.awt.Color(255, 255, 255));
        lblLine1.setText("Line 1:");

        txtLine1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtLine1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtLine2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtLine2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblLine2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblLine2.setForeground(new java.awt.Color(255, 255, 255));
        lblLine2.setText("Line 2:");

        lblCity.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblCity.setForeground(new java.awt.Color(255, 255, 255));
        lblCity.setText("City:");

        txtCity.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtCity.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblPostalCode.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblPostalCode.setForeground(new java.awt.Color(255, 255, 255));
        lblPostalCode.setText("Postal Code:");

        txtPostalCode.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtPostalCode.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblCellNo.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblCellNo.setForeground(new java.awt.Color(255, 255, 255));
        lblCellNo.setText("Cellphone No:");

        txtCellphoneNo.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtCellphoneNo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtEmail.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblEmail.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email:");

        javax.swing.GroupLayout pnlAddressInfoLayout = new javax.swing.GroupLayout(pnlAddressInfo);
        pnlAddressInfo.setLayout(pnlAddressInfoLayout);
        pnlAddressInfoLayout.setHorizontalGroup(
            pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddressInfoLayout.createSequentialGroup()
                .addGroup(pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddressInfoLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAddressInfoLayout.createSequentialGroup()
                                .addComponent(lblLine1)
                                .addGap(92, 92, 92)
                                .addComponent(txtLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAddressInfoLayout.createSequentialGroup()
                                .addGroup(pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLine2)
                                    .addComponent(lblCity)
                                    .addComponent(lblPostalCode))
                                .addGap(41, 41, 41)
                                .addGroup(pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAddressInfoLayout.createSequentialGroup()
                                .addGroup(pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCellNo)
                                    .addComponent(lblEmail))
                                .addGap(29, 29, 29)
                                .addGroup(pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(txtCellphoneNo)))))
                    .addGroup(pnlAddressInfoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblAddressInfo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAddressInfoLayout.setVerticalGroup(
            pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddressInfoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblAddressInfo)
                .addGap(35, 35, 35)
                .addGroup(pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLine1)
                    .addComponent(txtLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLine2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPostalCode)
                    .addComponent(txtPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCellNo)
                    .addComponent(txtCellphoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAddressInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addContainerGap())
        );

        lblIDNumber.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblIDNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblIDNumber.setText("ID Number:");

        txtIDNumber.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtIDNumber.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtIDNumber.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        cmbCampus.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        cmbCampus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pretoria", "Ekurhuleni", "Nelson Mandela Bay" }));
        cmbCampus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbCampusMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlUserInfo1Layout = new javax.swing.GroupLayout(pnlUserInfo1);
        pnlUserInfo1.setLayout(pnlUserInfo1Layout);
        pnlUserInfo1Layout.setHorizontalGroup(
            pnlUserInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserInfo1Layout.createSequentialGroup()
                .addGroup(pnlUserInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUserInfo1Layout.createSequentialGroup()
                        .addGroup(pnlUserInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUserInfo1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(lblUserInfoUpdate))
                            .addGroup(pnlUserInfo1Layout.createSequentialGroup()
                                .addGap(65, 77, Short.MAX_VALUE)
                                .addGroup(pnlUserInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserInfo1Layout.createSequentialGroup()
                                        .addComponent(lblLastnameUpdate)
                                        .addGap(63, 63, 63)
                                        .addComponent(txtLastnameUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserInfo1Layout.createSequentialGroup()
                                        .addComponent(lblFirstnameUpdate)
                                        .addGap(65, 65, 65)
                                        .addComponent(txtFirstnameUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserInfo1Layout.createSequentialGroup()
                                        .addGroup(pnlUserInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblIDNumber)
                                            .addComponent(lblCampusUpdate))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(pnlUserInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmbCampus, 0, 192, Short.MAX_VALUE)
                                            .addComponent(txtIDNumber))))))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserInfo1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlAddressInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(pnlLoginInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlUserInfo1Layout.setVerticalGroup(
            pnlUserInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserInfo1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblUserInfoUpdate)
                .addGap(18, 18, 18)
                .addGroup(pnlUserInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstnameUpdate)
                    .addComponent(txtFirstnameUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUserInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastnameUpdate)
                    .addComponent(txtLastnameUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUserInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDNumber)
                    .addComponent(txtIDNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUserInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampusUpdate)
                    .addComponent(cmbCampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(pnlAddressInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pnlLoginInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        txtSearch.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        txtSearch.setText("Search...");
        txtSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlRegisterHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 1500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 516, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSearch)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlUserInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlRegisterHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlUserInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jScrollPane1)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewUserActionPerformed
        frmViewUsers viewUser = new frmViewUsers();
        viewUser.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnViewUserActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        AdministratorMainDash mainDash = new AdministratorMainDash();
        mainDash.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    public User selectedUser;
    public String userPassword;
    private void lbxUsersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lbxUsersValueChanged
        int index = lbxUsers.getSelectedIndex();
        selectedUser = userList.get(index);
        Person person = selectedUser.getPerson();

        Address address = null;
        Contact contact = null;
        Department dep = null;

        try {
            Person per = person.selectSpecPerson();
            address = per.getAddress();
            contact = per.getContact();
            dep = per.getDepartment();

        } catch (SQLException se) {

        }
        txtFirstnameUpdate.setText(person.getName());
        txtFirstnameUpdate.setEditable(false);

        txtLastnameUpdate.setText(person.getSurname());
        txtLastnameUpdate.setEditable(false);

        txtIDNumber.setText(person.getId());
        txtIDNumber.setEditable(false);

        cmbCampus.setSelectedItem(person.getCampus());
        txtLine1.setText(address.getLine1());
        txtLine2.setText(address.getLine2());
        txtCity.setText(address.getCity());
        txtPostalCode.setText(address.getPostalCode());

        txtCellphoneNo.setText(contact.getCell());
        txtEmail.setText(contact.getEmail());

        cmbDepartment.setSelectedItem(dep.getName());
        txtUsername1.setText(selectedUser.getUsername());
        txtUsername1.setEditable(false);

        cmbAccessLevel.setSelectedItem(selectedUser.getAccessLevel());
        cmbStatus.setSelectedItem(selectedUser.getStatus());

        userPassword = selectedUser.getPassword();
    }//GEN-LAST:event_lbxUsersValueChanged

    private void btnEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUserActionPerformed
        //Variable Declaration
        String userFirstName="", userLastName="", userIDNumber="", userCampus="", addressLine1="", addressLine2="", addressCity="",
                contactCell="", contactEmail="", addressPostal="",
                userUsername="", userAccessLevel="", userStatus="", 
                departmentName="";
        User userToUpdate;
        Person personToUpdate;
        Address addressToUpdate;
        Contact contactToUpdate;
        Department deptToUpdate;

        Validation validation = new Validation();

        //Assigning values to variables
        userFirstName = txtFirstnameUpdate.getText();
        userLastName = txtLastnameUpdate.getText();
        userIDNumber = txtIDNumber.getText();
        
        if(cmbCampus.getSelectedItem().toString() != "")
        {
            userCampus = cmbCampus.getSelectedItem().toString();
            lblCampusUpdate.setForeground(Color.white);
            if(!"".equals(txtLine1.getText()))
            {
                addressLine1 = txtLine1.getText();
                lblLine1.setForeground(Color.white);
                if(!"".equals(txtLine2.getText()))
                {
                    addressLine2 = txtLine2.getText();
                    lblLine2.setForeground(Color.white);
                    if((validation.testProperString(txtCity.getText()))&&(!"".equals(txtCity.getText())))
                    {
                        addressCity = txtCity.getText();
                        lblCity.setForeground(Color.white);
                        if((validation.testNumericString(txtPostalCode.getText()))&&(!"".equals(txtPostalCode.getText())))
                        {
                            if(validation.testLength(txtPostalCode.getText(), 4, 4))
                            {
                                addressPostal = txtPostalCode.getText();
                                lblPostalCode.setForeground(Color.white);
                                if(validation.testNumericString(txtCellphoneNo.getText()))
                                {
                                    if(validation.testLength(txtCellphoneNo.getText(), 10, 10))
                                    {
                                         contactCell = txtCellphoneNo.getText();
                                         lblCellNo.setForeground(Color.white);
                                         char[] emailCharacters = new char[]{'@','.'};
                                         if((validation.testContains(txtEmail.getText(), emailCharacters))&&(!"".equals(txtEmail.getText())))
                                         {
                                              contactEmail = txtEmail.getText();
                                              lblEmail.setForeground(Color.white);
                                              if(!"".equals(cmbDepartment.getSelectedItem().toString()))
                                              {
                                                  departmentName = cmbDepartment.getSelectedItem().toString();
                                                  lblDepartment.setForeground(Color.white);
                                                  userUsername = txtUsername1.getText();
                                                  if(!"".equals(cmbAccessLevel.getSelectedItem().toString()))
                                                  {
                                                      userAccessLevel = cmbAccessLevel.getSelectedItem().toString();
                                                      lblAccessLevel1.setForeground(Color.white);
                                                      if(!"".equals(cmbStatus.getSelectedItem().toString()))
                                                      {
                                                          userStatus = cmbStatus.getSelectedItem().toString();
                                                          lblStatus1.setForeground(Color.white);
                                                      }
                                                      else
                                                      {
                                                          JOptionPane.showMessageDialog(null, "This field cannot be empty. Please Try Again!","Incorrect Status",JOptionPane.WARNING_MESSAGE);
                                                          lblStatus1.setForeground(Color.red);
                                                      }
                                                  }
                                                  else
                                                  {
                                                      JOptionPane.showMessageDialog(null, "This field cannot be empty. Please Try Again!","Incorrect Access Level",JOptionPane.WARNING_MESSAGE);
                                                      lblAccessLevel1.setForeground(Color.red);
                                                  }
                                              }
                                              else
                                              {
                                                  JOptionPane.showMessageDialog(null, "This field cannot be empty. Please Try Again!","Incorrect Department",JOptionPane.WARNING_MESSAGE);
                                                  lblDepartment.setForeground(Color.red);
                                              }
                                         }
                                         else
                                         {
                                             JOptionPane.showMessageDialog(null, "This is not a valid email address. Please Try Again!","Incorrect Email",JOptionPane.WARNING_MESSAGE);
                                             txtEmail.setText("");
                                             txtEmail.grabFocus();
                                             lblEmail.setForeground(Color.red);
                                         }
                                    }
                                    else
                                    {
                                        JOptionPane.showMessageDialog(null, "This field must contain 10 numeric characters. Please Try Again!","Incorrect Cellphone Number",JOptionPane.WARNING_MESSAGE);
                                        txtCellphoneNo.setText("");
                                        txtCellphoneNo.grabFocus();
                                        lblCellNo.setForeground(Color.red);
                                    }
                                }
                                else
                                {
                                    JOptionPane.showMessageDialog(null, "This field cannot be empty nor can it contain letters. Please Try Again!","Incorrect Cellphone Number",JOptionPane.WARNING_MESSAGE);
                                    txtCellphoneNo.setText("");
                                    txtCellphoneNo.grabFocus();
                                    lblCellNo.setForeground(Color.red);
                                }
                            }
                            else
                            {
                                  JOptionPane.showMessageDialog(null, "This field must contain 4 numeric characters. Please Try Again!","Incorrect Postal Code",JOptionPane.WARNING_MESSAGE);
                                  txtPostalCode.setText("");
                                  txtPostalCode.grabFocus();
                                  lblPostalCode.setForeground(Color.red);
                            }
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "This field cannot be empty nor can it contain letters. Please Try Again!","Incorrect Postal Code",JOptionPane.WARNING_MESSAGE);
                            txtPostalCode.setText("");
                            txtPostalCode.grabFocus();
                            lblPostalCode.setForeground(Color.red);
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "This field cannot be empty nor can it contain numberic characters. Please Try Again!","Incorrect City",JOptionPane.WARNING_MESSAGE);
                        txtCity.setText("");
                        txtCity.grabFocus();
                        lblCity.setForeground(Color.red);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "This field cannot be empty. Please Try Again!","Incorrect Address Line 2",JOptionPane.WARNING_MESSAGE);
                    txtLine2.setText("");
                    txtLine2.grabFocus();
                    lblLine2.setForeground(Color.red);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "This field cannot be empty. Please Try Again!","Incorrect Address Line 1",JOptionPane.WARNING_MESSAGE);
                txtLine1.setText("");
                txtLine1.grabFocus();
                lblLine1.setForeground(Color.red);
            }
        }
        else
        {
             JOptionPane.showMessageDialog(null, "This field cannot be empty. Please Try Again!","Incorrect Campus",JOptionPane.WARNING_MESSAGE);
             lblCampusUpdate.setForeground(Color.red);
        }

        addressToUpdate = new Address(addressLine1, addressLine2, addressCity, addressPostal);
        contactToUpdate = new Contact(contactCell, contactEmail);
        deptToUpdate = new Department(departmentName);
        personToUpdate = new Person(userFirstName, userLastName, userIDNumber, addressToUpdate, contactToUpdate, deptToUpdate, userCampus);
        userToUpdate = new User(personToUpdate, userUsername, userPassword, userAccessLevel, userStatus);

        if (userToUpdate.update() != -1) {
            if (personToUpdate.update() != -1) 
            {
                JOptionPane.showMessageDialog(null, "User was successfully updated!", "Successful Update", JOptionPane.INFORMATION_MESSAGE);
                    AdministratorMainDash mainDash = new AdministratorMainDash();
                    mainDash.setVisible(true);
                    this.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Error occured during this process!", "Unsuccessful Update", JOptionPane.ERROR_MESSAGE);
            }
        } 
        else 
        {
            JOptionPane.showMessageDialog(null, "Error occured during this process!", "Unsuccessful Update", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditUserActionPerformed

    private void cmbDepartmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbDepartmentMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDepartmentMouseClicked

    private void cmbCampusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbCampusMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCampusMouseClicked

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        frmAddUser addUser = new frmAddUser();
        addUser.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUpdateUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEditUser;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JButton btnViewUser;
    private javax.swing.JComboBox<String> cmbAccessLevel;
    private javax.swing.JComboBox<String> cmbCampus;
    private javax.swing.JComboBox<String> cmbDepartment;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAccessLevel1;
    private javax.swing.JLabel lblAddressInfo;
    private javax.swing.JLabel lblCampusUpdate;
    private javax.swing.JLabel lblCellNo;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblDepartmentInfo;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstnameUpdate;
    private javax.swing.JLabel lblIDNumber;
    private javax.swing.JLabel lblLastnameUpdate;
    private javax.swing.JLabel lblLine1;
    private javax.swing.JLabel lblLine2;
    private javax.swing.JLabel lblLoginInfo1;
    private javax.swing.JLabel lblPostalCode;
    private javax.swing.JLabel lblStatus1;
    private javax.swing.JLabel lblUpdateUser;
    private javax.swing.JLabel lblUserInfoUpdate;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JList<String> lbxUsers;
    private javax.swing.JPanel pnlAddressInfo;
    private javax.swing.JPanel pnlDepartmentInfo;
    private javax.swing.JPanel pnlLoginInfo1;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlRegisterHeader;
    private javax.swing.JPanel pnlRegisterHeader1;
    private javax.swing.JPanel pnlUserInfo1;
    private javax.swing.JTextField txtCellphoneNo;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstnameUpdate;
    private javax.swing.JTextField txtIDNumber;
    private javax.swing.JTextField txtLastnameUpdate;
    private javax.swing.JTextField txtLine1;
    private javax.swing.JTextField txtLine2;
    private javax.swing.JTextField txtPostalCode;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUsername1;
    // End of variables declaration//GEN-END:variables
}
